In [23]:
import numpy as np
import pandas as pd

Numpy

In [2]:
#1
a=np.array([[1,2,3,4,5],[1,2,3,4,5]])
b=np.array([[2,2,2,1,2],[2,2,2,2,2]])
result=a*b
print(a)
print(b)
print(result)

[[1 2 3 4 5]
 [1 2 3 4 5]]
[[2 2 2 1 2]
 [2 2 2 2 2]]
[[ 2  4  6  4 10]
 [ 2  4  6  8 10]]


In [3]:
#2
def find_missing_data(arr):
    missing_indices = np.isnan(arr)
    missing_values = arr[missing_indices]
    return missing_values

arr = np.array([1, 2, np.nan, 4, np.nan, 6])
missing_data = find_missing_data(arr)
print("Missing data:", missing_data)


Missing data: [nan nan]


In [4]:
#3
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([0, 40])

element_present = np.isin(array1, array2)

element_present

array([ True, False, False,  True, False])

In [6]:
#4
# Define a numpy array
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Save the array to a text file
np.savetxt('array.txt', array, fmt='%d')


In [7]:
#5
array = np.linspace(2.5, 6.5, 30)

array

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

Pandas

In [10]:
#1
series_of_lists = pd.Series([[1, 2, 3], [4, 5], [6, 7, 8, 9]])

flattened_series = series_of_lists.apply(pd.Series).stack().reset_index(drop=True)

flattened_series

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    8.0
8    9.0
dtype: float64

In [11]:
#2
series = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

subset_series = series[series > 5]

subset_series

6    6
7    7
8    8
9    9
dtype: int64

In [12]:
#3
series = pd.Series([1, 2, 3, 4, 5, 1, 2, 1, 1, 2, 2, 2, 3, 4, 5])

most_frequent = series.mode()[0]

modified_series = series.apply(lambda x: x if x == most_frequent else 'Other')

modified_series

0     Other
1         2
2     Other
3     Other
4     Other
5     Other
6         2
7     Other
8     Other
9         2
10        2
11        2
12    Other
13    Other
14    Other
dtype: object

In [13]:
#4
series = pd.Series([1, 2, 5, 7, 10, 12, 15, 20, 25])

positions = np.where(series % 5 == 0)[0]

positions

array([2, 4, 6, 7, 8], dtype=int64)

In [14]:
#5
series = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])

char_counts = series.apply(len)

char_counts

0     5
1     6
2     6
3     4
4    10
dtype: int64

In [15]:
#6
series = pd.Series(['2021-01', '2021-02', '2021-03', '2021-04'])

day_of_month = 15

dates = pd.to_datetime(series).dt.date + pd.to_timedelta(day_of_month - 1, unit='D')

dates

0    2021-01-15
1    2021-02-15
2    2021-03-15
3    2021-04-15
dtype: object

In [16]:
#7
data = {
    'Name': ['John', 'Alice', 'Bob', 'Diana'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
index_labels = ['A', 'B', 'C', 'D']


df = pd.DataFrame(data, index=index_labels)

print(df)

    Name  Age         City
A   John   25     New York
B  Alice   30  Los Angeles
C    Bob   35      Chicago
D  Diana   40      Houston


In [17]:
#8
data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

selected_rows = df[df['attempts'] > 2]

selected_rows

name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

In [19]:
#9
new_row = {'name': 'Samantha', 'score': 21.5, 'attempts': 1, 'qualify': 'yes'}
df.loc['k'] = new_row

appended_df = df.copy()

df.drop('k', inplace=True)

appended_df, df

(        name  score  attempts qualify
 a  Anastasia   12.5         1     yes
 b       Dima    9.0         3      no
 c  Katherine   16.5         2     yes
 d      James    NaN         3      no
 e      Emily    9.0         2      no
 f    Michael   20.0         3     yes
 g    Matthew   14.5         1     yes
 h      Laura    NaN         1      no
 i      Kevin    8.0         2      no
 j      Jonas   19.0         1     yes
 k   Samantha   21.5         1     yes,
         name  score  attempts qualify
 a  Anastasia   12.5         1     yes
 b       Dima    9.0         3      no
 c  Katherine   16.5         2     yes
 d      James    NaN         3      no
 e      Emily    9.0         2      no
 f    Michael   20.0         3     yes
 g    Matthew   14.5         1     yes
 h      Laura    NaN         1      no
 i      Kevin    8.0         2      no
 j      Jonas   19.0         1     yes)

In [20]:
#10
sorted_df = df.sort_values(by=['name', 'score'], ascending=[False, True])

sorted_df

name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

In [21]:
#11
df['qualify'] = df['qualify'].map({'yes': True, 'no': False})

df

name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

In [22]:
#12
data = {
    'A': [1, 2, np.inf, -np.inf],
    'B': [np.inf, 3, 4, np.inf],
    'C': [1, 2, 3, 4]
}
df_inf = pd.DataFrame(data)

df_inf.replace([np.inf, -np.inf], np.nan, inplace=True)

df_inf

A    B  C
0  1.0  NaN  1
1  2.0  3.0  2
2  NaN  4.0  3
3  NaN  NaN  4